version: '2'

services:
  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    expose:
      - "6379"
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  helper:
    image: vinbrain.azurecr.io/lung-segmentation:develop.88
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    expose:
      - "8080"
volumes:
  redis_data:
    driver: local
