version: '2'

services:
  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    expose:
      - "6379"
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  helper:
    image: measurementtutorial.azurecr.io/lung-segmentation:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    expose:
      - "8080"
  # chest-segmentation:
  #   image: measurementtutorial.azurecr.io/chest-segmentation-cxx:latest
  #   environment:
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     LUNGMASK_URL: http://helper:8080/images
  #   expose:
  #     - "8080"
  chest-detection-0:
    image: measurementtutorial.azurecr.io/chest-detection-cxx:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PREDICT_PIPELINES: nofinding,mdevice,edema,cavitation,covid
      HELPER_PIPELINES: all
      LUNGMASK_URL: http://helper:8080/images
      CHEST_SEG_URL: http://chest-segmentation:8080/images
    expose:
      - "8080"
#   chest-detection-1:
#     image: measurementtutorial.azurecr.io/chest-detection-cxx:latest
#     environment:
#       REDIS_HOST: redis
#       REDIS_PORT: 6379
#       PREDICT_PIPELINES: cls,tubercolusis
#       HELPER_PIPELINES: all
#       LUNGMASK_URL: http://helper:8080/images
#       CHEST_SEG_URL: http://chest-segmentation:8080/images
#     expose:
#       - "8080"
  chest-ai-proxy:
    image: measurementtutorial.azurecr.io/chest-ai-proxy:latest
    depends_on:
      - redis
      - helper
#       - chest-segmentation
      - chest-detection-0
#       - chest-detection-1
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CHEST_DETECTION_URLS: http://chest-detection-0:8080/images; # http://chest-detection-1:8080/images
#       CHEST_SEGMENTATION_URLS: http://chest-segmentation:8080/images
      CHEST_HELPER_URL: http://helper:8080/images
      CACHE_ENCODE: jpg
    ports:
      - "8080:8080"
    volumes:
      - /home:/home


volumes:
  redis_data:
    driver: local


#     docker push measurementtutorial.azurecr.io/chest-ai-proxy:latest
# docker push measurementtutorial.azurecr.io/lung-segmentation:latest
# docker push measurementtutorial.azurecr.io/chest-detection-cxx:latest
